services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false


    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
#    docono\Bundle\SeoBundle\Controller\:
#        resource: '../../Controller'
#        public: true
#        tags: ['controller.service_arguments']

    dcc.cconsent:
        class: docono\Bundle\DccBundle\CConsent

    docono\Bundle\DccBundle\CConsent: '@dcc.cconsent'

    dcc.templating.dcc:
        class: docono\Bundle\DccBundle\Templating\Helper\Dcc
        public: true
        tags:
            - { name: templating.helper, alias: dcc }

    docono\Bundle\DccBundle\Twig\TemplatingHelperExtension:
        shared: true
        arguments:
            - '@dcc.templating.dcc'
